### ISSUE TITLE
DV8 Integration Functions - Nicholas

### ISSUE THREAD

**Issue by nicoelee123** [sailuh/kaiaulu#169]
This issue is a follow up to Issue #165 

Pull Request: https://github.com/sailuh/kaiaulu/pull/176

### Milestone 3.3

- [x] dv8_gitlog_to_gitnumstat() (performs gitlog –numstat –date=iso)
- [x] dv8_gitnumstat_to_hdsmb() (scm:history:gittxt:convert-matrix)
- [x] dv8_hsdsmb_to_decoupling_level() (metrics:decoupling-level)
- [x] dv8_hsdsmb_to_hierclsxb() (dr-hier:dr-hier)
- [x] dv8_hsdsmb_drhier_to_excel() (office:export-spreadsheet)
- [x]  dv8_dsmb_to_dsmj() (core:export-matrix)
- [x] parse_dv8_metrics_decoupling_level()

**Comment by carlosparadis** [comment]
Hi Nico,

Thanks. Could you update the checkboxes to match the function names in #165?

**Comment by nicoelee123** [comment]
Hello @carlosparadis,

I'm currently working on the function parse_dv8_metrics_decoupling_level(). I was wondering how you'd want the output. For example did you want the metric returned by the function, or printed straight onto the console?

**Comment by carlosparadis** [comment]
The function should return a data.table object, much like the output of parse_gitlog() and parse_mbox(). If I remember correctly, the actual output of the DL command is fairly simple, with a 1 line json of 3 attributes, so you only need to use the jsonlite function to parse it, then format as a data.table and return :)

**Comment by carlosparadis** [comment]
@nicoelee123 I see you have marked all but this function as done, but I do not see a PR. Did I miss it? Otherwise, please send completed functions as you go, so as to give me more time to do revisions, as asked in my e-mail. We want to parallelize this as much as possible.

Thanks!
