### ISSUE TITLE
Create a fake data generator for git logs 

### ISSUE THREAD

**Issue by carlosparadis** [sailuh/kaiaulu#227]
Edit: I am editing the top message so it is easier to navigate this issue. Prior message is below. 

# Task List

The goal here is to refactor the Git Sample Function:

https://github.com/sailuh/kaiaulu/blob/cb2f4098d6aeedb1cf3721a4de75803fe97145f1/R/git.R#L125-L180

## Step 1 

The following are the functions that should be refactored out of it:

 - [ ] io_create_folder #233 
 - [ ] io_make_sample_file #233
 - [ ] git_init #233
 - [ ] git_add #232
 - [ ] git_commit  #232

## Step 2.1

Create a new module in Kaiaulu, R/example.R and define some example repos. 

 - [x] A repo which was git init, but with no commits. 
 - [x] One commit in two different with branches with 1 file each (may need to improve the existing `git_checkout` function)
 - [x] A repo with 3 commits. The first adds hello.R. The second renames the file to `hi.R`. The third adds a second file `bye.R`. 

## Step 2.2

Add associated unit tests to the above to `parse_gitlog()`.

## Step 3 

Add the following unit tests

 - [x] A repo with 3 commits, where 1 file has as prefix `_test.R`, 1 file has the suffix `example_*.R`, and 1 file hello.R.
 - [x] A repo with 2 commits, one containing 5 files modified, and the other containing only one. (Rationale: Can test 

Note the unit tests are not associate dto `parse_gitlog()`. 

# Prior Message

In hindsight, a bigger contribution for this project is to improve the setUp and tearDown we have than just add more unit tests without this available (they are far too restricted as is). We will start making one for Git as some code is already available, and then we can swap to Jira in a later week.

## Background on setUp and tearDown in R 

The relevant background information can be found on this chapter: https://r-pkgs.org/testing-advanced.html#create-and-destroy-a-local-useful_thing (this has been referenced on call before. I suggest reading up to and including the section referenced).

Kaiaulu currently has a rudimentary setUp and tearDown function for Git logs: https://github.com/sailuh/kaiaulu/blob/6ff61e558cb2b2a658dc90c93649d41ab3f30022/R/git.R#L110-L201 

## Adding a few more setUp functions 

Our initial goal is to refactor this monolithic function into a few more functions for greater control: 

 * **io_make_sample_file <- function(save_filepath,body)**:  Should take as input the save filepath and the body, and create a file. (Place it on R/io.R)

The code for this function is already there:

https://github.com/sailuh/kaiaulu/blob/6ff61e558cb2b2a658dc90c93649d41ab3f30022/R/git.R#L139-L145

You just need to parameterize it. Please do the same for each of the other system2 calls in that functions and parameterize them. Make sure you include proper documentation using the syntax from other functions. You can compile the docs using Cmd (or Ctrl) + Shift + D, then subsequently compiling it (Cmd (or Ctrl) + Shift + B).

This should give you also the functions:

 * **io_create_folder** (place in R/io.R)
 * **git_init**
 * **git_add** 
 * **git_commit**

The git functions should go in R/git.R

For `git_commit` you should include two additional parameters to the function, `author` and `email` which accept a string containing that information.
To specify a different author and e-mail on commit, you can use: https://stackoverflow.com/questions/3696938/how-do-you-commit-code-as-a-different-user 

## Refactor git create sample log

https://github.com/sailuh/kaiaulu/blob/6ff61e558cb2b2a658dc90c93649d41ab3f30022/R/git.R#L125 

With the additional functions added, replace the system call with the functions you created. If you have questions on this, please post directly on this issue.

## Pull Request

Please pull request the code before our next tag in **Kaiaulu**. How-to is here: https://github.com/sailuh/kaiaulu/blob/master/CONTRIBUTING.md

**Comment by carlosparadis** [comment]
@waylonho @Rubegen 

Proceeding with this issue, the goal is to expand the function you both refactored, `git_create_sample_log`. The goal here is to enable us to write unit tests for `parse_gitlog`. 

There is a tool similar to Kaiaulu, called Codeface, which you can see an example of how this would look like which @nicolehoess shared with me after our call.

# 1. Fake Data in Codeface

## 1.1 Creating Examples using a Fake Data Generator Class

https://github.com/lfd/codeface/blob/e6640c931f76e82719982318a5cd6facf1f3df48/codeface/test/integration/example_projects.py#L21-L135 

You will see an example `project` is defined from the `GitProject` class. Browsing through the file, you will find a few 
other example functions. Each produce a dataset for a different purpose of testing. E.g.

https://github.com/lfd/codeface/blob/e6640c931f76e82719982318a5cd6facf1f3df48/codeface/test/integration/example_projects.py#L137C5-L142

> This project is an example where the mailing list is too monotonous for
    codeface and several calculations fail. Since this is unlikely to happen
    in any real project, we leave it at that for the moment

## 1.2 The Class which Creates Fake Data

You can see what this GitProject definition is here:

https://github.com/lfd/codeface/blob/e6640c931f76e82719982318a5cd6facf1f3df48/codeface/test/integration/gitproject.py#L41-L45

>  Represents a Git repository with utility methods to create fake 
> histories with fake authors, committers, rc and release tags. 
> To get a physical git repository, use an instance of ExampleProject as 
> a context manager using the with statement.  This ensures that the git 
> repository is properly deleted at the end of testing. 

Notice the class `GitProject` is not the unit tests. Its purpose is to generate fake data, importantly, on the fly. 
You can see from the example created using GitProject, that different methods of the class can be called
to customize the fake data, including author, commit message, and even e-mails. You can examine the 
functions of GitProject to see it has a template of the content, with some parts being parametrized.

Your goal with  

https://github.com/sailuh/kaiaulu/blob/6ff61e558cb2b2a658dc90c93649d41ab3f30022/R/git.R#L125

Is to create something similar, albeit simpler, only considering the git log, such that someone using your
function can define example fake data as done in 

https://github.com/lfd/codeface/blob/e6640c931f76e82719982318a5cd6facf1f3df48/codeface/test/integration/example_projects.py#L21-L135

## 1.3. The Unit Tests

If you notice the location of the code above, you will see its path under `codeface/test/integration`. 

 * gitproject.py: Defines the class that can create fake data (GitProject) (The git_sample in Kaiaulu fits this role)
 * example_projects.py: Calls the GitProject class to define some example datasets.  (This would be the next step)
 * The files `test_logger.py`, `test_features.py` and `test_exampleprojects.py` are the unit tests. In particular, the later seems to leverage the fake data of `example_projects.py`. I guess one example here could be:

```python
class TestEndToEndExample2Proximity(EndToEndTestSetup, TestEndToEnd):
    example_project = 2
    tagging = "proximity"
    add_ignore_tables = ["edgelist"]
    devs = ["Louie Loner", "Geoff Genius", "Bill Bully", "Max Maintainer",
            "Adam Awkward", "Peter Popular", "Clara Confident"]
    correct_edges = [[[devs[0], devs[5], 1.0],
                      [devs[1], devs[6], 1.0],
                      [devs[2], devs[4], 1.0],
                      [devs[3], devs[2], 1.0],
                      [devs[3], devs[4], 1.0],
                      [devs[4], devs[2], 1.0],
                      [devs[5], devs[0], 1.0]]]
```

You can see the example_project2 is used to generate fake data, and this class sets forth a set of expectation of what the output should be. This example is less than ideal for us here since this is an end-to-end test, but you can see there are overall 3 parts this story:

 * The class that offers functions to generate fake data
 * The examples of fake data which uses said class, and are annotated with the rationale of a particular dataset
 * The unit tests which tests the tool code against said fake data 

# 2. Kaiaulu 

## 2.1 Fake Data in Kaiaulu

Going back to our case you must first:

 * Improve the git_sample function so it can more reliable produce fake data. 
 * Write some example fake data functions using git_sample and finally
 * Write some some unit tests for parse_gitlog by calling the fake data over it, and testing its output table against the expected value.

Please post questions here if not clear.

**Comment by Rubegen** [comment]
Hi Carlos,
I'm currently looking at the comments you left on my pull request for this issue. Now that I have a better understanding, the parametrization makes sense and I am working on fixing the code now. 
One question that I need clarification on for now, 
"With the additional functions added, replace the system call with the functions you created" could you expand on this point, I'm not sure what should be changed once the functions are implemented properly.

**Comment by carlosparadis** [comment]
Great! 

To answer your question, take for example:

https://github.com/sailuh/kaiaulu/blob/6ff61e558cb2b2a658dc90c93649d41ab3f30022/R/git.R#L130-L134

This is a system call (system2 function). You got this code and made a function out of it. All I am saying is that you should now erase the system2 portion you made the function for, and use the function instead :) That's exactly why you made the function in the first place.

What you both are doing on this Pull Request is the "Extract Function" refactoring: https://refactoring.com/catalog/extractFunction.html 

You need to do this first, before you can move forward on creating a more _flexible_ function to create fake git log data. Does that make sense?

**Comment by waylonho** [comment]
Hi. This is what we have currently for example.R for step 2.1. We will discuss this in the meeting shortly, but thought it'd be good to post directly to the issue just to make sure the line of thinking is correct:

![5dd81d0f0d110d779d3366fb873587bf](https://github.com/sailuh/kaiaulu/assets/84744515/139dd449-f182-4cc2-a553-97453f5b540b)

Some of the syntax for the functions are off and we are working on changing the git_checkout. But basically:

Repo 1: we create a folder with io_create_folder, then use git_init
Repo 2: edit git_checkout, work in progress
Repo 3: create folder, git_init, create hello.R, add hello.R, commit. Then rename the file, commit, Then create bye.R, add bye.R, commit. 

We're slightly behind but will have this step done ideally tonight / before the end of the weekend and get into the next steps right away.

**Comment by carlosparadis** [comment]
PRs #232 and #233 addresses this issue.
