### ISSUE TITLE
Abstract Config file parsing in R/config.R

### ISSUE THREAD

**Issue by carlosparadis** [sailuh/kaiaulu#230]
Currently, modifying the /conf file schema requires checking every Notebook in Kaiaulu to make sure it still parses the project's yaml file correctly. The logic behind understanding the config file should be abstracted in a set of get methods, to de-couple all the Notebooks from it. 

The coupling doesn't occur if it is adding fields, but any substantial re-organization will cause a mass co-change cascade. This should also help document the config file as R functions, and in the future write some utilities to analyze config files (e.g. a paper's project demographics could go here, since it would borrow info from the config to compute the latex table).

**Comment by anthonyjlau** [comment]
# 1. Purpose
The purpose of this issue is to create get functions for configuration files. The motivation for this is that in each notebook in the vignettes folder, it loads in the config files by using a variable assignment (i.e. `mbox_path <- conf[["mailing_list"]][["mbox"]]`). If we were to change the structure of the config file (i.e. rename "mailing_list" to something else or move the variable elsewhere), then we would have to go though each notebook that uses it and change it so that it goes to the right value. To solve this, I am creating the file R/config.R to centralize the process of getting values from config files.

# 2. Process
This will be done by creating get methods for all of the config files that will be used in the notebooks. Then, I replace the direct variable assignment with the get methods in R/config.R.

# 3. Task List
- [ ] Find out which config files I need to make get methods for.
- [ ] Create R/config.R and make the get methods for each config file.
- [ ] Replace the variable assignments in each notebook with my getter methods.

**Comment by carlosparadis** [comment]
@anthonyjlau Looks great!

**Comment by carlosparadis** [comment]
@anthonyjlau One more thing: Make sure you post here the function API nomenclature (i.e. update the first issue following the template). It would be a lot of time waste on your end if you went with a function nomenclature I would like to modify, as you would need to modify every notebook to fix that thereafter.

**Comment by anthonyjlau** [comment]
@Ssunoo2 @ian-lastname Ensure that the configs that are used on this project are in the final version and work with config.R. This includes the projects for the mailing lists (@ian-lastname), the ones used for Jira and Github (@Ssunoo2) and the ones for Bugzilla (@anthonyjlau).

**Comment by crepesAlot** [comment]
### 1. Purpose
--------------------------
Currently, the Notebooks (.Rmd files in the /vignettes folder) have hard coded file paths connected to the .yml files in the /conf folder.
This means that by reorganizing or editing the folder or files within it, a lot of problems could occur unless you were to manually go in each Notebook and update any of the changed values.
Thus, it needs to be configured such that the R/config.R file will be able to automatically update any Notebooks should any changes occur.
### 2. Process
----------------------------
The process will be to follow the previous solution, creating get functions within the config file and then replace the direct variable assignments within Notebooks with said get functions.
### 3. Task List
----------------------------

- [ ] Confirm the required get methods
- [ ] Add any missing get methods
- [ ] Test to get methods work
- [ ] Replace any and all file path assignments with the get methods from the config file
- [ ] Ensure reorganization doesn't cause issues

**Comment by crepesAlot** [comment]
### Questions
-------------------

1.  Was there anything about the prior approach you didn't like, or something you want us to do differently?
2.  Were there any notes or information discovered by @anthonyjlau that are important for us to know before we get started?

**Comment by beydlern** [comment]
### Questions
-------------------

1.  Was there anything about the prior approach you didn't like, or something you want us to do differently?
2.  Were there any notes or information discovered by @anthonyjlau that are important for us to know before we get started?

**Comment by carlosparadis** [comment]
@beydlern 

I now realize the other half of the issue lies on #286, which is why this task requires two of you to work on it, sorry for the confusion. You need to read through that to get a better idea of why this task requires two of you.

The purpose statement in https://github.com/sailuh/kaiaulu/issues/230#issuecomment-2345383394 is a bit fuzzy. For example:

> This means that by refactoring the folder or files within it, a lot of problems could occur unless you were to manually go in each Notebook and update any of the changed values. 

What is the problem that occurs by hardcoding paths instead of using get() from a config.R? 

> R/config.R file will be able to automatically update any Notebooks should any changes occur.

I am not sure what you mean by config.R automatically updating the Notebooks. How would this occur? 

Consider the purpose for Anthony's task to refine your specification on purpose. As for the get methods you need, which Anthony implemented a couple, 

-----

To put in a nutshell: The other issue mentions that the way Kaiaulu specify project configuration files should be extended, to account for more edge cases. To extend the specification of configs, that means all configs on conf/ should be updated. This is purely a documentation task, no code involved. 

What you will notice, however, is that the moment you update these config files in conf/ another problem cascades: Because the paths in every notebook are hardcoded to specific paths in the config files, now every notebook has to be updated. If we ever need to extend the specification of the config again (which will happen to include other tools parameters), then once more, every notebook has to be updated. This is not a good organization. 

To address this "config specification change cascades into every notebook being updated", we want to instead call the get() functions of conf.R at the start of the notebooks, which is the goal of this issue, instead of hardcode the content of the config files. This means if all conf/ files have to be updated again, then only the implementation of the get() functions in conf.R have to be updated for the portions of the config files that are changed (so a subset of the functions), the notebooks do not need to do so, since the get functions implementation change, but the function definition and return are the same. 

The lesson here is Information Hiding. See: https://en.wikipedia.org/wiki/Information_hiding 

With that understanding, I would like you both to have a task specification edited above, with what each of you will be working on. Your purpose statement is the same, but you should make it more clear who wil work on conf.R and who will update the notebooks (or you may split this in half and half, it is your call). Note @daomcgill and @RavenMarQ will need to understand your work, as they will have a notebook for the mail downloader, and one for scitools understand that depend on the new config format and your get functions.

p.s.: I would be mindful of pinging others on this issue who are not working on the task, as that may trigger e-mail notifications for them!

**Comment by beydlern** [comment]
@carlosparadis May you review the updated specifications?

**Comment by carlosparadis** [comment]
@beydlern sorry, edits do not send notifications, did you just update or did I miss this for a few days?

**Comment by beydlern** [comment]
I edited my specifications today, would you like me to revert the edit and post it as new one?

**Comment by carlosparadis** [comment]
No, it's alright. We can actually see the edits if we click the "edited" word in the message. Keep them in one comment. I will get back to you on it then, wanted to make sure I did not overlook!

**Comment by beydlern** [comment]
### Question
In part of this notebook's [_gitlog_entity_showcase_parallel.Rmd](https://github.com/sailuh/kaiaulu/blob/230-abstract-config-file-parsing/vignettes/_gitlog_entity_showcase_parallel.Rmd#L67) project configuration file section, would this hardcoding to a specific save path `save_path <- "../../results/spark"` need to be refactored into a get function?

**Comment by carlosparadis** [comment]
@beydlern  in my original email i mentioned notebooks with _ prefix should be ignored for this task!

**Comment by carlosparadis** [comment]
Also, as far as specification goes, the get() methods are not defined in them. The understanding is correct, but without the  signature and parameters as requested I can't assess. I recall Anthony had a couple if not all done. I am also not clear on the task division between you both (was it posted?). I'd suggest start changing them on the notebooks to test if it works, and send one commit with a notebook with the get functions and config.R. Beware that since you both have the same branch, you can't both push. I recommend one of you decide who will push to the PR, and the other keeps a copy so you can both merge locally.

**Comment by beydlern** [comment]
I edited my specification to include the function signature and parameters. The task division should be detailed in our task list comments: Mark will focus on the new config file specifications to follow the [folder organization](https://github.com/sailuh/kaiaulu_cheatsheet/blob/main/cheatsheets/refresher-cheatsheet.pdf). I will focus on the implementation of the get() functions and replacing the hard-coded paths in the notebooks with these get() functions.

**Comment by crepesAlot** [comment]
@carlosparadis I updated my comment with what is currently done for the conf files, is this along the lines of what you were looking for?

**Comment by carlosparadis** [comment]
You should include the comment of your specification on follow-up, this is a long issue to try to track down: https://github.com/sailuh/kaiaulu/issues/230#issuecomment-2345383394 

>  This means that by refactoring the folder or files within it, a problem of needing to manually go in each and every Notebook and update any of the changed values.

I don't believe this is quite there yet. Why and when the problem happens? This is a bit vague.

>  The projectName being listed before github would allow easy access to every folder for a project.

Same here, stating "easy access" is too general, a number of different approaches could lead to "easy access". 

> The Anomaly Case 1 would be addressed in the case for jira by adding extra depth after the project key. It was decided that Anomaly Case 2 wasn't a concern with the above structure.

Your specification has to be self contained. You can either expand on it, or reference it. Otherwise, nobody else will know what you are referring to here.

Your config file still refers to mail_key_1. 

Needs revision, but you should get started. It is important you understand why the changes, and at least in the specification it seems like it is not clear. I am not sure if it is the wording or the understanding.

**Comment by beydlern** [comment]
@carlosparadis I made a [commit](https://github.com/sailuh/kaiaulu/commit/f9d20ec05d9d830ef881bfc797a7244acc2dc256) that should reflect the review comments made on the pull request. The get functions should follow the correct function documentation.

**Comment by crepesAlot** [comment]
### Question
----------------
I was discussing with @daomcgill about the mailing list and found some things I wanted clarification on.
On [this](https://github.com/sailuh/kaiaulu/issues/284#issuecomment-2351838281) comment for issue #284, you stated:

> If so this is fine, except we should change from mail_key_1 to just project_key_1 etc for consistency with the other downloaders (you will want to defer this to the pair working on the project config, but just to make sure we are all on the same page). Pipermail should also have multiple project keys, similar to mod_mbox.

However, on [this](https://github.com/sailuh/kaiaulu/issues/286#issuecomment-2041252245) comment for issue #286, you had originally stated: 

> I modified the config above so it tries to stay consistent with the folder depth of the other downloaders and account for the information needed for the functions. I also changed from project_key_1 to mail_key_1 since they are all from the same project, but just the mailing list that serves a different purpose.

As of right now, Dao's mailing list looks something like:
```
mailing_list:
  mod_mbox:
    mail_key_1:
      mailing_list: https://lists.apache.org/list.html?announce@apache.org
      start_year_month: 202310
      end_year_month: 202405
      save_folder_path: "../save_mbox_mail"
    mail_key_2:
      mailing_list: https://lists.apache.org/list.html?dev@felix.apache.org
      start_year_month: 202201
      end_year_month: 202401
      save_folder_path: "../save_mbox_mail"
  pipermail:
    project_key_1:
      # archive_url: https://mta.openssl.org/mailman/listinfo/
      mailing_list: https://mta.openssl.org/pipermail/openssl-users/
      start_year_month: 202310
      end_year_month: 202405
      save_folder_path: "../save_folder_mail"
    project_key_2:
      # archive_url: https://mta.openssl.org/mailman/listinfo/
      mailing_list: https://mta.openssl.org/pipermail/openssl-project/
      start_year_month: 202203
      end_year_month: 202303
      save_folder_path: "../save_folder_mail_2"
```
I find the inconsistency between having a mail_key_1 for mod_mbox and a project_key_1 for pipermail to be rather confusing, and am not sure if it should be kept this way. If it should be changed, which of the two should we be changing it to?
Secondly, I want to confirm that the save_folder_path should also reflect a similar folder organization as the [cheatsheet](https://github.com/sailuh/kaiaulu_cheatsheet/blob/main/cheatsheets/refresher-cheatsheet.pdf)
Something like:
```
../../rawdata/helix/mod_mbox/save_folder_mail
../../rawdata/helix/mod_mbox/save_folder_mail_2
../../rawdata/helix/pipermail/save_folder_mail
../../rawdata/helix/pipermail/save_folder_mail_2
```

**Comment by carlosparadis** [comment]
Everything should be project_key. 

Reasoning this out of the paths is hard. Could you try to create the folder organization and post a screenshot here? The original idea was that the refresher folder is for a particular mailing list and type (e.g. user, dev) so that the logic would not be overly complicate (e.g. if you mix in a dev and user mailing list then the refresher logic will become more convoluted).

**Comment by carlosparadis** [comment]
@beydlern  Does this include the notebooks or that is still WIP? https://github.com/sailuh/kaiaulu/issues/230#issuecomment-2373848374

**Comment by beydlern** [comment]
@carlosparadis This is still a WIP. The next commit I push should have the correct function descriptions and titles as well as all of the appropriate notebooks updated to use the get functions. @daomcgill made great suggestions to my function documentation in her comment, they may be viewed in the [pull request](https://github.com/sailuh/kaiaulu/pull/288).

**Comment by beydlern** [comment]
@carlosparadis May you briefly review my functions and the `download_github_comments.Rmd` problem?

**Comment by carlosparadis** [comment]
You want to be more descriptive on the issue rather than the "`download_github_comments.Rmd` problem" . Assuming you are referring to GitHub Actions check and tests not passing: 

If you click to see the log from the check, you will see the problem is on line 84:

> https://github.com/sailuh/kaiaulu/actions/runs/11091955004/job/30816372193#step:11:72 

This is not an issue with your code, but something setup on GitHub actions that only I can fix. What you can and should do is run the "check" in your own computer, and ensure it passes.

**Comment by crepesAlot** [comment]
@carlosparadis Here is a quick diagram for the folder organization. I tried to organize it to make it easier to understand.
![Folder Organization Diagram ](https://github.com/user-attachments/assets/7cdad48b-1afc-4788-bfef-b459f1d8c087)
The save_mail_folder is per mailing list, so each mailing list should have its own folder. Thus, there shouldn't be an issue of a dev mailing list getting mixed with a user mailing list within the same folder. 
After discussing with Dao, my understanding is that there are more types of mailing lists than for just devs and users (such as announcements), so we won't be able to create a specific folder name for each type. The user will have to define what folder is used for each type.

**Comment by beydlern** [comment]
In the `download_github_comments.Rmd` notebook, there is a problem that is detailed in the latter half of my comment.

> @carlosparadis . . . There are still notebooks that pose some issues, such as the [`download_github_comments.Rmd`](https://github.com/sailuh/kaiaulu/blob/230-abstract-config-file-parsing/vignettes/download_github_comments.Rmd#L48) notebook that holds references to the old configuration file GitHub issue tracker replies section [`kaiaulu.yml`](https://github.com/sailuh/kaiaulu/blob/master/conf/kaiaulu.yml#L68). In this specific case, `save_path` can't be removed from `download_github_comments.Rmd` because it is [used later on](https://github.com/sailuh/kaiaulu/blob/230-abstract-config-file-parsing/vignettes/download_github_comments.Rmd#L193) in an external parsing function that builds upon this path.

Should I modify this parsing function `parse_github_replies()` to work with the updated config in the notebook?

**Comment by carlosparadis** [comment]
@crepesAlot  https://github.com/sailuh/kaiaulu/issues/230#issuecomment-2387559750

Well done! You are correct, thank you for checking with @daomcgill

Could you share the editable file if we need to extend in the future?

**Comment by carlosparadis** [comment]
@beydlern not sure I understand the issue on https://github.com/sailuh/kaiaulu/issues/230#issuecomment-2387587833 

The dependency of the function is on save_path, a string, not the config file. If your get function is used in the start of the notebook to load save_path string, then what is the issue?

**Comment by beydlern** [comment]
@carlosparadis The problem I face is that I cannot load save_path because the updated kaiaulu.yml config file doesn't contain the "replies" path anymore. `conf[["issue_tracker"]][["github"]][["replies"]]` field in line 48 of `download_github_comments.Rmd` doesn't exist in the current kaiaulu.yml config file. A remedy would be to delete `save_path <- path.expand(conf[["issue_tracker"]][["github"]][["replies"]])` from [line 48](https://github.com/sailuh/kaiaulu/blob/230-abstract-config-file-parsing/vignettes/download_github_comments.Rmd#L48), and modify the function in [line 193](https://github.com/sailuh/kaiaulu/blob/230-abstract-config-file-parsing/vignettes/download_github_comments.Rmd#L193) `replies <- parse_github_replies(save_path)` to take in four parameters for the issue, pull_request, issue_or_pr_comment, and commit folders as well as modify the `parse_github_replies()` function in [`github.R`](https://github.com/sailuh/kaiaulu/blob/230-abstract-config-file-parsing/R/github.R#L17C1-L17C21). 

I would like to know if I am permitted to modify other files to work with the new config files and getter functions. In this case, I would need to modify the function `parse_github_replies()` in `github.R`.

**Comment by carlosparadis** [comment]
@beydlern  I think you are trying to fix a problem on the GitHub Notebook when the issue lies in the config file specification itself. 

@crepesAlot The image of the paths for download may actually be incorrect. The GitHub Downloader that is more current is sitting on a PR on this repo. 

The path forward lies here:

https://github.com/sailuh/kaiaulu/blob/a0b3619e602077f8299019f8955f88b973575dc9/vignettes/download_github_comments.Rmd#L52 

In GitHub, the endpoint that gives you "replies", i.e. literally our comments on this issue or a pull request, is the endpoint above. So save_path should be loading that. I do not know why the paths on the folder image do not include that, is the configuration file specification incorrect?

**Comment by carlosparadis** [comment]
The variable `save_path` should be replaced with https://github.com/sailuh/kaiaulu/blob/a0b3619e602077f8299019f8955f88b973575dc9/vignettes/download_github_comments.Rmd#L52 

>  I'm not supposed to ensure functionality of the notebooks, just replace the hard-coded paths with the getter functions, in accordance with my task specifications? 

Correct, I do not expect you are able to run, but I do expect _I_ will be able to run. For that to happen, you need to ensure the get methods being replaced still return the correct string in changing the config file specification.

**Comment by carlosparadis** [comment]
@beydlern the link points to the Notebook currently on `master`. However, you should be looking at the GitHub PR here: https://github.com/sailuh/kaiaulu/pull/289 

It was not merged because I was missing the new project configuration file being integrated to all Notebooks. The JIRA refresh was merged to `master`, however.

You will also want to update the Bugzilla Notebook on the PR: https://github.com/sailuh/kaiaulu/pull/293 

My suggestion is that you make a commit on the respective PRs updating their Notebooks to expect the new config file format. I will merge this PR first, so when those two are merge to `master`, they will lead to the new state of `master` working with the notebook properly. 

On the other hand if you try to commit those notebooks on this PR, it will be a mess, so be careful to not mix the different codes in the PR. 

Also, I will note that while M1 does not require you to understand the Notebooks or run them, M2 will for one of you. But in the interest of time, you can skip that for the time being.

Thank you for the attention to detail on the parameters, it is greatly appreciated.

**Comment by crepesAlot** [comment]
@carlosparadis I have updated the Folder Organization Diagram, adding a section for the third party tool analysis filepaths and the bugzilla file path in the issue_tracker.
![Folder Organization Diagram](https://github.com/user-attachments/assets/7b4792c9-9bde-47b5-aee2-038af6bf071e)
### Github
The issue_or_pr_comment for github only gets the replies to the issue or pr comment, so it is missing the initial comment made by the author.
Thus, issue and pull_request are necessary to retrieve the "first comment"
issue_events is used to get the events, which is can later be used to subset issue assignments.
commit gets the information from the commits.
I was unable to understand what issue_search is for.
### Bugzilla
My understanding is that it downloads a file that contains both the issue and comments, and then parses through it to separate them.
Thus, it would need a folder for issues, and a folder for the comments (issue_comments).
This can look like:
```
bugzilla:
   project_key_1:
      project_key: ambari
      issues: ../../rawdata/ambari/bugzilla/issues/ambari/
      issue_comments: ../../rawdata/ambari/bugzilla/issue_comments/ambari/
```
----------------------
I did have some concerns with some of the changes I made, and would appreciate it if you could vet it before I make a commit.
Firstly, I moved the git_repo folder to be inside the project folder, to make it more consistent with the rest of the structure.
This would look like:
```
../../rawdata/junit5/git_repo/.git
```
Which was previously:
```
../../rawdata/git_repo/junit5/.git
```
Second, I moved the pattern4 tool analysis save file path from the git_repo folder to the analysis folder (where the other tools are directed to). I also added a output_filepath, which was previously non-existent (yet there was a getter function for it on Config.R).
I don't understand how the tool works and am concerned as to why the file path was extremely long, or if changing it would cause any issues or errors.
In any case, my proposed change is:
```
../../rawdata/junit5/analysis/pattern4/classes/
../../rawdata/junit5/analysis/pattern4/output/
```
Which was previously:
```
../../rawdata/git_repo/junit5/junit-platform-engine/build/classes/java/main/org/junit/platform/engine/
```
Lastly, I don't quite understand what is meant by your earlier comment of: 

> I have not yet seen the function that creates the folder directory structure using your diagram as reference. We want said function in config.R

I wasn't aware I was supposed to be creating any functions, but to clarify you want me to make functions for each of the folder directories?

**Comment by carlosparadis** [comment]
>  I was unable to understand what issue_search is for.

This is partially a fault of GitHub. The rationale should have been added on the issue_search endpoint. Did you find the function documentation lacking or the notebook? That should be on the GitHub PR. We may need to expand.

Basically, the key difference has to do with the refresh capability of GitHub (ask @daomcgill to go over refresh with you if needed). There is a very subtle trap (for the lack of better word) in regards of what is considered the start date on most endpoints other than the search endpoint. See https://github.com/sailuh/kaiaulu/issues/282#issuecomment-2052634711 and https://github.com/sailuh/kaiaulu/issues/282#issuecomment-2052657178 

So using refresh with other endpoint than the search would start adding duplicate entries (see final conclusion here: https://github.com/sailuh/kaiaulu/issues/282#issuecomment-2076547610). 

> Firstly, I moved the git_repo folder to be inside the project folder, to make it more consistent with the rest of the structure.
This would look like: 

This should have been the case, the specification you started from may not be the final agreed one or this was missed (can you check if the cheatsheet bottom left tree did not include that?)

Pattern4:

> Second, I moved the pattern4 tool analysis save file path from the git_repo folder to the analysis folder (where the other tools are directed to). I also added a output_filepath, which was previously non-existent (yet there was a getter function for it on Config.R).
> I don't understand how the tool works and am concerned as to why the file path was extremely long, or if changing it would cause any issues or errors. In any case, my proposed change is:

> `../../rawdata/junit5/analysis/pattern4/classes/`

This does not make sense. The "analysis" is not "rawdata". The "analysis" folder should be side by side to the "rawdata" folder. 

What goes in the "analysis" folder is complicated. You see that @RavenMarQ is adding a new tool to Kaiaulu to interface with. This does not affect the rawdata folder per se (the input for Scitools is the src code in `git_repo`), but that does affect the `analysis` folder (it is new output). 

My suggestion for now is that you simply break the folder path inside analysis to be one folder per tool. What goes inside of them, we can delegate to the tool itself. There is also the question of "do we display a table on the notebook, or do we write it?"

Most of the Notebooks written had a mix of both, and analysis was build organically to reflect that. @daomcgill wrote a /exec script for mbox, and I expect other execs to be written as part of your M2. What we know for certain will be saved to disk, rather than rendered in the notebook, is what /exec scripts produce. So, I think when we finish M2, what goes in the analysis folder will be more clear: It will just conform to the existing /exec scripts output, and not the Notebooks themselves. 

The function of config.R that creates the folder structure proposed by Kaiaulu, represented in your diagram, therefore, for now, can just create the analysis folder, and the subfolders per tool. We can revisit it at the end of M2.

>  I have not yet seen the function that creates the folder directory structure using your diagram as reference. We want said function in config.R
 
You can treat this as part of M2. Just keep in mind we will need it. A diagram so the users can reason the folder hierarchy is good and needed (it will make its way to a cheatsheet eventually). But a function that does it all for the user, is where it really benefits and saves everyone's time.

-----

Let me know if I missed anything. I appreciate your attention to detail and rigor in the questions made. It demonstrates good mastery of what you know and what you realize you may not know yet to fill the gaps. This was really good!

**Comment by crepesAlot** [comment]
@carlosparadis Here is the updated file organization diagram, with the analysis file path being equal to the rawdata path on the right side.
![Folder Organization Diagram (1)](https://github.com/user-attachments/assets/290d6f08-a720-43a0-b1ee-45208932078a)
I moved the tools input files back to the git_repo folder where they were originally and fixed the output analysis folder to be outside the rawdata folder.

**Comment by carlosparadis** [comment]
This is great, thanks! However, when I mention "on the side" i meant if you were staring at the actual folder window. In your diagram, what you want to do is put the "analysis" tree all the way below rawdata, so it is clear they are at the same level in the directory hierarchy. 

Once you have that, make sure to add the editable to google drive too (remove the old to avoid confusion). This will be a great foundation for M2 discussions for this: https://github.com/sailuh/kaiaulu/issues/226#issuecomment-1782481820 

One more point: Of the diagram you made, which regions in it you feel fuzzy on what they are for? This will be important for M2 too.

Good work :)

**Comment by carlosparadis** [comment]
To be clear: When I say "all the way below rawdata", i mean it will appear below the lowest box in the image you have, so below git_repo, but aligned to the rawdata horizontal position.

**Comment by crepesAlot** [comment]
Unfortunately I attempted that, but it seems there was a limit to how low I'm allowed to expand the google images, and am unable to add anything below the tools section. I was hesitant to start shrinking everything down to make it fit, but if you'd prefer that, I can do so.
@beydlern is waiting on my commit to create and update get functions for bugzilla and scitools understanding.
I wanted to make sure that the current folder organization and do the scitools understanding config section before making the commit.

**Comment by beydlern** [comment]
@carlosparadis The GitHub PR #289 notebooks were updated to use the getter functions in config.R. These notebooks are currently using the new specification. Currently waiting for @crepesAlot to finish the config specification for Bugzilla so I may ensure that the Bugzilla notebook in the Bugzilla PR #293 follows the correct new specification.

**Comment by carlosparadis** [comment]
@beydlern thank you for the update. Somewhere in the issue sea of comments I recall answering a question about the difference of issue search and just `issue`, was that clear or still confusing? Maybe it was @crepesAlot question.

**Comment by carlosparadis** [comment]
@crepesAlot the updated https://github.com/sailuh/kaiaulu/issues/230#issuecomment-2401210035 is not here yet, did you create it?

**Comment by crepesAlot** [comment]
@carlosparadis Here is a screenshot of the powerpoint version of the folder organization. The google drawings version has also been updated.
![Kaiaulu Folder Organization](https://github.com/user-attachments/assets/4b0aad23-8bd5-439e-b688-94592b1ca1fd)
Here is a link to the powerpoint slide:
https://1drv.ms/p/c/abff49bde83c4541/EVMVEyD7CxVPpX7DcvCKv7MB6yoQKqB3UINnOuXcBWfqrg?e=nb9QKG

**Comment by carlosparadis** [comment]
@crepesAlot  I had to make a few modifications on the actual config. Could you take a look on Kaiaulu and Helix config on my last two commits to see the differences? Here's two examples. It has mostly to do with the inner folders. Also the current use of  /.git towards the end without it being in a folder with git log. While editing I realized that would not work well, because when a user downloads .git data, they generally use git clone. That means the source code comes along with the .git, which in turn means the folder of the source code always sit above one level of .git (I do not have a screenshot for this here, if not clear you can ask me on call).

In addition to that you can see I reverted the deepest folder: 

![Image](https://github.com/user-attachments/assets/195f74c1-d042-41f8-932f-737269d52793)

![Image](https://github.com/user-attachments/assets/0ee4991f-c07d-4a0f-8029-e1549c29f9f6)

We may need to do some edits on the diagram to reflect this. Let me know what you think. @beydlern pinging you too on this since you worked on this on M1 to make sure we are on the same page. This may also affect @daomcgill  PR. Will take a look on it next. 

This may need another pass on the configs to fix the consistency (I only had time to fix the ones Kaiaulu needs on the notebooks that run).
