### ISSUE TITLE
JIRA Parser (Milestone 1)

### ISSUE THREAD

**Issue by ian-lastname** [sailuh/kaiaulu#276]
## 1. Purpose
I need to create a parser that takes in the json files created by the new Jira Downloader to be parsed into a table format. There is a pre-existing jira_parser already: (https://github.com/sailuh/kaiaulu/blob/9294a9bb92506b76424b0fcc7c07f6b74d5ce53d/R/parser.R#L820C1-L917C2)
so I'll most likely be editing this already existing code so that it adheres to the new requirements.

## 2. Fields of Interest

> See https://github.com/sailuh/kaiaulu/issues/152#issuecomment-1441314400. It must be clear what fields are currently parsed, and what fields must be added. Keep the reference and port the table to this issue to expand upon.

| Current fields used |
| - |
| title (summary) |
| issuekey |
| issuetype |
| components |
| creator |
| created |
| description |
| reporter |
| status |
| resolution |
| resolutiondate |
| assignee |
| updated |
| comment |

| Fields to be added |
| - |
| parent (ADDED) |
| priority (ADDED) |
| labels (ADDED) |
| fixVersions (ADDED) |

## 3. Refresh Capability

The parser will go through the names of each file in the save folder, and extract the upper-bound unix time as seen in this naming schema: “[projectkey]_issues_[Lower-BoundUNIXtime]_[Upper-BoundUNIXtime].json”. With the extracted numbers in a list, it will then find the maximum among them and reformat it to “YYYY-MM-DD” and return it with the other returned data. The returned data is all in a list called parsed_issue_comments. I will add the latest date to this list so that Sean’s refresher may access the latest created date by calling something like parse_jira(file_path)[[“latest_date”]]. I’ve debated whether I should keep it in the parse_jira function or if I should just make it its own function; I don’t see any problem in keeping it in parse_jira. If there are any problems with this that you can think of, I can easily just make it a separate function.

## 4. Existing API for Bugzilla and GitHub 

Bugzilla and GitHub parser APIs both make use of functions within the main function to actually parse the issues and comments. The Buglzilla API parser function itself does use a Boolean parameter to determine if comments will be parsed as well. Both return table data. 

The Bugzilla parse makes use of an internal "bugzilla_parse_comment" and "bugzilla_parse_issue" functions that are found within the main parser function found [Here](https://github.com/sailuh/kaiaulu/blob/9294a9bb92506b76424b0fcc7c07f6b74d5ce53d/R/parser.R#L21) and [Here](https://github.com/sailuh/kaiaulu/blob/9294a9bb92506b76424b0fcc7c07f6b74d5ce53d/R/parser.R#L68) respectively. The issues and comments are then obtained in a loop found [Here](https://github.com/sailuh/kaiaulu/blob/9294a9bb92506b76424b0fcc7c07f6b74d5ce53d/R/parser.R#L114). 

As for the existing GitHub API, it seems to do a similar process in which the main parsing function calls other functions to do the actual parsing found [Here](https://github.com/sailuh/kaiaulu/blob/9294a9bb92506b76424b0fcc7c07f6b74d5ce53d/R/parser.R#L1018), [Here](https://github.com/sailuh/kaiaulu/blob/9294a9bb92506b76424b0fcc7c07f6b74d5ce53d/R/parser.R#L1025), and [Here](https://github.com/sailuh/kaiaulu/blob/9294a9bb92506b76424b0fcc7c07f6b74d5ce53d/R/parser.R#L1032). As you can see in these lines of code, it is applying a specific parser function on a json file. The overall idea behind it is the same as Bugzilla, but is executed a bit differently

### Step 1
/R/parser.R/parse_jira_new(json_path) [THE NAME "new" IS TEMPORARY]:
- [x] This function takes a file path that contains all the json files to be parsed. It will then read a json file and parse all the issues in that json file, returning a list containing two elements: 1) table data for the issues, 2) table data for the issue_comments.

- [x] Reading the bugzilla and GitHub parser functions, I’ve noticed that they put the part of the code that actually parses the issues in its own function within the main function. So, I will move all the code that parses the issue into its own function called “jira_parse_issues(json_file)” or something to that effect. This follows the naming convention for other issue parsers within the main parser functions for Bugzilla and GitHub.

- [x] Add functionality so that it can create a list of the files found within the file directory obtained from the json_path parameter. Using said list, it will apply the “jira_parse_issues(json_file)” over the files found in json_path, parsing all issues and getting all that parsed issue data into a list. It will return the list. The returning list will be containing two elements: 1) table data for the issues, 2) table data for the issue_comments.

- [x] Functionality where the latest time range is obtained and returned. It will be obtained from the file names of the json files. (MOVED TO 'parse_jira_latest_date(json_path)')

- [x] Add extra fields as specified in point 2: fields of interest

###Step 2
/R/parser.R/parse_jira_latest_date(json_path)
- [x] Create a function that takes the save file paths of jira issues, parses the names of the json files, and finds the latest date that an issue was created from the names. Returns said date.

**Comment by carlosparadis** [comment]
See: https://github.com/sailuh/kaiaulu/issues/228

You will a also want to start practicing the parser using Kaiaulu's JIRA Sandbox.

**Comment by ian-lastname** [comment]
Alright, so I’ve come to realize that because Sean’s new downloader puts each issue in its own individual json file, differentiating whether to parse the json files with comments or json files without comments just got a bit more complicated. Before, with the original downloader, the issues downloaded with comments and issues downloaded without comments were all together in their respective json files, and those json files could be easily pointed to by just putting in their respective pathway into the parser function. Now with Sean’s downloader, they’re all out in the same directory. Since I have to iterate over each file to parse them individually, there’s a possibility that my function will just iterate through all of the json files indiscriminately, parsing both the comment and comment-less issues at the same time.

I have two proposals to prevent this from happening:
1. Create two separate folders in the usual pathway to house the comment and comment-less json files separately. The way I see it, it works similarly to how the original downloader saved the json files for each issue. The new folders represents the original json files that the issue data resides in, and the data in this case would be the new json files that Sean’s downloader creates.
2. Create an extra parameter in my parser function that dictates whether to parse the issue_comments json files or the comment-less json files. It’d be something like parse_jira(path, a). For example, should parameter “a” be a string “comment”, then the function will only read the json files that were created with a comments field.

**Comment by carlosparadis** [comment]
@ian-lastname Iterating over the set of files you wish for can be done with the `list.files` function in a directory. This will give you the list of filepaths as a character vector. You can then use stringi library to pattern match the elements of the character vector which file name are used for comments (you have to have different file name conventions for those with and without comments).

However, before you pursue this, I strongly advise you to do what I recommended and edit post 1 using the proposed change template. Without that, I can't assess what functions you are trying to write. We may need to re-do again at the end of the week if it does not match what it should be. You should also ask @Ssunoo2 to post on his issue plan how the folder organization he expects should be before proceeding further so we can discuss it here.

**Comment by ian-lastname** [comment]
So I take it that something like my 2nd proposal would be the way to go? I want to preface this with that I’m just trying to find a way for the function to know when it wants to parse the comment-less jsons and the comment jsons.

**Comment by carlosparadis** [comment]
See, I'm not sure what you mean by creating two folders in option 1 since, technically, this decision should been discussed on the plan of the downloader. Your second proposal is about whether you should add a parameter or not to a function: I also can't respond, since I don't know the scope of functions you plan to do. Please have the group post these specifications ASAP so I can help you decide what makes the most sense. You 3 also likely want to compare notes so the specifications are not conflicting. 

On the meantime, what you should focus on is ensuring your parser can download the JSON data straight from the browser using the endpoints I provided, and which results in a table equivalent to the one we currently have (note, the parsed table we currently have, not the JSON). Have you tested that yet? 

Also, the refresh capability depends primarily on you code logic on how to parse the file names. I would like to see how you plan to organize that into functions too. The downloader should be able to download a specified time range or issue range, but who passes the information to it on what range it should use, would be logic by the parser.

**Comment by ian-lastname** [comment]
I downloaded the json data directly from the browser (didn’t make my parser do it, I manually did it). I then tested my parser by making it read that json data, which resulted in a table equivalent to the one created by download_jira_data.rmd (as in, the original downloader).

**Comment by carlosparadis** [comment]
@ian-lastname Great, then the next step is begin the pull request so I can start performing code reviews :)

**Comment by carlosparadis** [comment]
@ian-lastname Also, the first comment still does not follow the specification, so may want to work on that first. For the review, choose another team member via the interface. Once they give a pass, and the GitHub Actions also is a pass, request mine.

**Comment by ian-lastname** [comment]
Does my first comment follow the specifications now?

**Comment by ian-lastname** [comment]
Just to clarify, other than how my issue is written, my code seems fine up until this point right?

Also, am I expected to put all the parsed information into an actual .csv file?

**Comment by carlosparadis** [comment]
In reply to: https://github.com/sailuh/kaiaulu/issues/276#issuecomment-1953538027

The step 1 is missing the filepath of where the function resides, and I can see you are diverging from the API on your second step. I added a section to your issue for you to check how the GitHub and Bugzilla functions are so we can go from there.  

In reply to: https://github.com/sailuh/kaiaulu/issues/276#issuecomment-1955247877 

I have not reviewed your code yet, since the specification still is not clear and some functions should not exist. Strictly speaking, your functions should be replacing the existing ones in the Download Notebook, to the extent ideally no code has to even be changed there, save perhaps the refresh aspect of it.

**Comment by ian-lastname** [comment]
Okay I updated the issue tracker 1, I know I still have to do point 2 but I at least made it more clear (hopefully) on what I’m doing for my function.

**Comment by carlosparadis** [comment]
Still have some good bit of work to go on the issue specification. Contrast yours to @Ssunoo2. Function enumeration and handshake still missing. That being said, you are respecting the template which makes easier to understand. Just need to add the missing specification.

**Comment by ian-lastname** [comment]
Updated my issue tracker thing, doubt that I’ve done enough, still going through with it. Just want to explain that when I do find the latest date, I plan to return it by doing this basically:
‘
returningList <- list()
returningList[[“issues”]] <- all_issues
returningList[[“comments””]] <- all_issue_comments
returningList[[“latest_date”]] <- latest_date
return(returningList)
‘

So, Sean can get the latest date for the refresher via an assignment to parse_jira(save_path)[[“latest_date”]]. This is what I have now (aside from the method of obtaining the latest data, which is something I’ll change)

**Comment by ian-lastname** [comment]
Okay, so I was investigating my failures in the unit checks and I'm getting these three failures:
![failed_test](https://github.com/sailuh/kaiaulu/assets/97856957/66e54bb1-a9ef-4baa-a857-7d8d1a49dc2f)

The test results indicates that 0 rows are being made with parse_jira; when I call nrow(issues) in something download_jira.rmd, it returns the expected amount of rows.

I tried figuring this out myself, then I remembered that this is a bad thing so I am now asking for your assistance.
Also, for the record all I've been doing before initiating unit checks are rebuilding the package and documentation, not sure if there's anything else I need to do.

Also, the other failures I'm getting is pertaining to unrelated stuff: perceval and mbox for the gitlog functions

**Comment by ian-lastname** [comment]
Okay so I've fixed the errors for the non-jira things, turns out I forgot to fix my perceval location when I transferred my work to my forked repository. Still, I'm getting those failures on the parse_jira tests. I've read [here](https://github.com/sailuh/kaiaulu/issues/277#issuecomment-1936128722): "The Fake Data Generator that tests the parser function is therefore dependent on JirAgileR." Does this mean that the unit tests and checks are still using/making test issues that follow the old format? If so, do I just ignore these failed checks?

**Comment by ian-lastname** [comment]
I've added the fields of interests, made the latest date finding part of the parse_jira function into its own function, and I restored the old parse_function so that the unit tests and checks would pass, now the new jira parser is found in 'parse_jira_new'.

**Comment by ian-lastname** [comment]
I have gotten more specific on how the Bugzilla and Github parsers work, providing links to the lines of code that I am taking inspiration from for the Jira parser.

**Comment by anthonyjlau** [comment]
@carlosparadis @ian-lastname  This is a reminder to check that issues are able to parse when there are missing fields in the issue. For example, this [issue](https://issues.apache.org/jira/browse/WW-2883) does not have a description field. Check to see if this causes the table to break or causes other errors.

**Comment by carlosparadis** [comment]
Reviewing this one, please don't push any commits. Adding notes here as I go:

https://issues.apache.org/jira/rest/api/2/search?jql=project=SPARK%20AND%20issueKey%20%3E=%20SPARK-33953%20AND%20issueKey%20%3C=%20SPARK-33955 

This worked fine: Fields are blank when necessary, issues table filled, comments table not filled (as intended since no comments data).

https://issues.apache.org/jira/rest/api/2/search?fields=comment&jql=project=SPARK%20AND%20issueKey%20%3E=%20SPARK-33953%20AND%20issueKey%20%3C=%20SPARK-33955

This does **not** work: The comments table is parsed, but the issues table only parses the issue ids.

**Comment by carlosparadis** [comment]
Inclusion of the `comments` field ommits all other fields. May be worthwhile including a `stop` later cautioning of that, but it should be avoided if it was done using our downloaders instead of ad-hoc.

The fields from the downloader are:

"summary,description,creator,assignee,reporter,issuetype,status,resolution,components,created,updated,resolutiondate"

Therefore editing the query to explicit them when requesting comments leads the prior comments URL to be:

https://issues.apache.org/jira/rest/api/2/search?fields=comment,summary,description,creator,assignee,reporter,issuetype,status,resolution,components,created,updated,resolutiondate&jql=project=SPARK%20AND%20issueKey%20%3E=%20SPARK-33953%20AND%20issueKey%20%3C=%20SPARK-33955

The issue affects version, fix Versions and issue labels remain empty but now 22 columns are reported. When using the endpoint without `comment`, 25 columns are reported. Therefore, some of the fields that should be explicit are likely missing in the downloader.

Comparing both columns, the fields missing are:

"issue_priority" "issue_votes"    "issue_watchers"

**Comment by carlosparadis** [comment]
https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issue-fields/#api-group-issue-fields

Which can then be used on Apache using:

https://issues.apache.org/jira/rest/api/2/field

Using this to find the text value of the fields I have:

* priority
* votes
* watches

Apparently the following fields are also missing on the Notebook:

* versions
* fixVersions
* labels


Adding these to the url then we have:

https://issues.apache.org/jira/rest/api/2/search?fields=comment,summary,description,creator,assignee,reporter,issuetype,status,resolution,components,created,updated,resolutiondate,votes,watches,priority,versions,labels,fixVersions&jql=project=SPARK%20AND%20issueKey%20%3E=%20SPARK-33953%20AND%20issueKey%20%3C=%20SPARK-33955

**Comment by carlosparadis** [comment]
Spark does not use Labels, but Hadoop does. To test labels, following URL works:

https://issues.apache.org/jira/projects/HADOOP/issues/HADOOP-14451?filter=allopenissues

https://issues.apache.org/jira/rest/api/2/search?fields=comment,summary,description,creator,assignee,reporter,issuetype,status,resolution,components,created,updated,resolutiondate,votes,watches,priority,versions,labels,fixVersions&jql=project=HADOOP%20AND%20issueKey%20%3E=%20HADOOP-14451%20AND%20issueKey%20%3C=%20HADOOP-14453

Error occurs: Subscription out of bounds.

**Comment by carlosparadis** [comment]
Should be fixed, but I can't find a JIRA issue with more than one label to be sure. @ian-lastname see if you can find one.

**Comment by carlosparadis** [comment]
#281 is merged. Checks are intentionally failing since they rely on the Downloader and JIRA Fake Data Generator which are dependent on JirAgileR. This should be fixed on the subsequent commits. 

Will re-open the issue if something blows up, but manual tests for issues, comments and some final fixes were performed before merge.
