### ISSUE TITLE
Fake Data Generator (Milestone 1) 

### ISSUE THREAD

**Issue by anthonyjlau** [sailuh/kaiaulu#277]
## 1. **Purpose**

The purpose of this issue (https://github.com/sailuh/kaiaulu/issues/277) is to recreate the existing fake JIRA issue generator without the JirAgileR formatting. This means that the base_info_cell and ext_info_cell will be removed and the raw data will be formatted the same way that it would be normally downloaded.  

## 2. Fields of Interest

![jsonfields](https://github.com/sailuh/kaiaulu/assets/98019016/42816b5e-68a6-4911-bec9-b35b1c7b6d86)
| Fields being generated |
| - |
| jira_domain_url |
| issue_key |
| project_key |
| summary |
| description |
| issue_type |
| resolution |
| priority |
| status |
| labels |
| components |
| affects_versions |
| fix_versions |
| assignee_name |
| creator_name |
| creator_name |
| reporter_name |
| parent |
| priority |
| labels |
| fixVersions |
| project |

## **Task List**

**Step 1**
- [x] jira.R/make_jira_issue_new(jira_domain_url, issue_key, issue_type, status, resolution, title, description, components, creator_name, reporter_name, assignee_name, comments = NULL): This function takes as parameter information about a JIRA issue and returns a JIRA issue as a list in the proper raw data format.

**Step 2**
- [ ] jira.R/make_jira_issue_tracker_new(issues, save_filepath): This function takes as parameter a list of issues that are generated from make_jira_issue_new, writes it to a JSON file, and saves it at the save_filepath.

**Step 3**
- [ ] jira-test.R: create unit tests that create a JSON file and check to see if the format is the exact same as the API call. 

### **Notes from call on 2/19/24**

The old fake Jira issue generator had many problems with the indentation of the values so it had to be flattened in order to match the JirAgileR data. My job is to recreate the fake JIRA issue generator so that the information about the issues is in the exact same spots as the raw data.

**Comment by anthonyjlau** [comment]
**My plan for the fake data generator:**

- [ ] Look at fake data cheat sheet and other issues/ discussions about the fake data generator
- [ ] Read through the current fake data generators to try and understand them
- [ ] Write a mailing list data generator
- [ ] Write a git data generator
- [ ] Write a JIRA data generator
- [ ] Combine the generators to make fake projects
- [ ] Make unit tests that check the projects

**Comment by anthonyjlau** [comment]
As mentioned previously, I was wondering if I am supposed to be redoing that fake data generator with a new API or am I expanding on what they have done already? I wrote down that we were using the HTTR api but I forget if that was for the other parts of the milestone.

**Comment by carlosparadis** [comment]
I would not call for an extension but rather a replacement. The basic issue is https://github.com/sailuh/kaiaulu/issues/228. Here's why we need to replace: We are currently relying on JirAgileR to download the issue data. The Fake Data Generator that tests the parser function is therefore dependent on JirAgileR. 

Unfortunately, this package modifies the raw data one would obtain from the issue tracker. The Fake JIRA Issue Generator for the issue tracker, therefore, ended up dependent on a data format of JirAgileR, instead of JIRA. Since we are replacing JirAgileR by our own crawler, we should also adjust the JIRA Fake Issue Data Generator accordingly. 

You should be able to reuse most of the existing code, but there are some fixes and improvements that should be made.

Also important to keep in mind: https://github.com/sailuh/kaiaulu/issues/258

**Comment by anthonyjlau** [comment]
Hi @carlosparadis, as I mentioned on call, I had some questions about the fake Jira issue generator. In jira.R, there are many functions that "flatten" the data. I was wondering what that meant? Issue #251 address it but it does not explain it. We also talked about the many headers in the raw data that I need to address. I was wondering what my scope is for the data that I should generate and which headers can be ignored?

**Comment by carlosparadis** [comment]
@anthonyjlau Here's what's going on. 

When the task was originally assigned, I created a sample issue function for the milestone to start from. That function is here:

https://github.com/sailuh/kaiaulu/blob/81f57f875a61606ef66c2aa77deb18972dabe18c/R/jira.R

The idea was then that this function evolved to a proper fake data generator by parametrizing it. More importantly, when this R list gets saved as a json using jsonlite::write_json() function, it has to match exactly the JSON object you would download from the API via the browser. 

It seems however, there was a mistake on this sample log, and therefore, when the function evolved into the fake data generator, the depth of the elements were not correct. For example:

https://github.com/sailuh/kaiaulu/blob/81f57f875a61606ef66c2aa77deb18972dabe18c/R/jira.R#L36-L53

You can see how some elements are inside empty list() calls. You have to carefully compare if that will generate the equivalent JSON. Because this was not the case, then, when it came the time to combine individual issues into a multiple issues JSON file, the JSONs did not so easily combine. This in turn required all cells to be parsed out to then be inserted in a new file, which is entirely unecessary and makes unreadable code. 

You therefore have to verify each element of the JSON being generated in the individual function, save to a JSON and triple check that the format matches exactly. 

I would like you to try and organize your first issue towards assessing that and how you will combine the individual issues into a single JSON. Please also list all the functions you plan to create so I am sure we are on the same page.

**Comment by carlosparadis** [comment]
@anthonyjlau I have added a fields of interest section to your issue, as you also brought up last call. This should be made very explicit in the issue, since we want to add a few more compared to the older issue tracker. I listed an issue to help you get started. This is where the Kaiaulu jira sandbox will help you.

**Comment by carlosparadis** [comment]
@anthonyjlau You will be replacing the existing issue tracker functions, so no need to create functions suffixed by _new. We will no longer support jirAgileR. 

Because of that, I expect your changes to work seamlessly with the example functions and unit tests that are already in place without requiring any modification. If something is already breaking, let me know. The bulk of your effort will be to fix the issue that led to the flattening, and also add new fields, those which you have to iterate with me here based on what you believe is missing from the sandbox. I need to see the table I am requesting you and @ian-lastname to do, so maybe you an share with him the effort.

**Comment by carlosparadis** [comment]
As noted on discord: Try to create simpler, basic lists to pinpoint what is forcing the 0s to appear. We need to figure out how to create the list in R that does not generate the 0 on writejson, rather than rely on a transformation of writejson to band-aid the problem introduced on the list creation.

**Comment by anthonyjlau** [comment]
I have been testing with simple lists and even different data types, such as data frames, to fix the formatting but each time it would still end up with 0s.

I looked online and found a helpful [website](https://www.lexjansen.com/pharmasug-cn/2021/SR/Pharmasug-China-2021-SR031.pdf) that goes over jsonlite and the mapping between JSON data and R objects. On page 3 of the paper, under the **_special cases: vectors of length 0 or 1_** section, it says that vectors of length 1 are put into an array of length 1. The outputs of the examples on the page also show the vectors of length 1 outputting as an array of length 1 which causes the 0 indexes. It might sound kind of lazy but I think that the way that jsonlite maps the R data to JSON is the cause of the 0s. I was also looking through the source code of jsonlite and found a [file for converting lists to JSON](https://github.com/jeroen/jsonlite/blob/0134cba18366b1c51c6497f4f97273a8423d8d86/R/asJSON.list.R
). Below are examples of the differences in the raw data between the API call and my test JSON file.

![image](https://github.com/sailuh/kaiaulu/assets/98019016/88b21048-451d-4098-b03f-937714a9fbb5)
^ In the API raw data, there is no []'s between the key-value pairs.

![image](https://github.com/sailuh/kaiaulu/assets/98019016/bf7c094c-9d7a-4f21-8648-19bff84867db)
^ In this simple list, there are []'s between the key-value pairs. I think this is what causes the 0 indexes.

I am stuck as to figuring out how to format this properly without the jsonlite transformations so your advice on this would be appreciated!

**Comment by carlosparadis** [comment]
If this is truly the case, then we have our culprit for the mismatch. My suggestion is therefore that you use auto_box since you do have full control over the list in memory you are creating, but @Ssunoo2 entirely avoids going through jsonlite to store the data (but can use it to obtain information to format file name). @Ssunoo2  should be able to save it "as is" when downloaded, as we somehow managed to in one case earlier today. Please just make sure that in using auto_box other variables do not get affected.

Less than ideal, but maybe down the road I can find a library that is able to preserve original formats, or just like JirAgileR, end up having to make something native ourselves.

Thanks for noting this down here.
