### ISSUE TITLE
Making Parsed Source Code Data Available Externally

### ISSUE THREAD

**Issue by daomcgill** [sailuh/kaiaulu#314]
-----

## Purpose 

This issue is an extension of [issue #313](https://github.com/sailuh/kaiaulu/issues/313). The purpose here is to create configurable /exec scripts that make data tables available externally. The new scripts will add usability to the syntax extraction process by providing a usable way to perform source code annotations and XML querying.

## Process
1. Create script for annotating source code using srcML.
2. Create script for querying the annotated data. This will accept a predefined query or a user-defined XPath query.
3. Documentation

## New Scripts
/exec/syntaxextractor.R: Script for running the syntax extractor using existing functions in R/src.R. The functionality for this is split into two parts:
1. Annotation: Takes in a source code folder and uses srcML to generate an annotated XML file. 
2. Querying: Accept predefined XPath queries to extract syntactic elements from the XML files. Allows custom XPath queries to be specified by the user. Outputs the query results.

## Task List 
- [ ] Prerequisite: completion of issue #313
- [ ] Create a new script in /exec
- [ ] Implement functionality for annotation
- [ ] Implement functionality for queries
- [ ] Documentation: explain how to use exec scripts, configuration and parameters

-----

**Comment by daomcgill** [comment]
@carlosparadis part II

**Comment by carlosparadis** [comment]
@daomcgill For this one I would consider making two execs, one that annotates, and the other that can query the file. Annotating can take a long time depending on the size of the project, hence the split. 

Otherwise, I think this is good! We can take another pass once #313 is done. 

Thanks!

**Comment by daomcgill** [comment]
@carlosparadis I have added exec scripts for annotating and parsing. I have, however, had issues with defining a generic function that can take any XPath query as an argument. The generic solution would have to accommodate distinct xml structures with differing hierarchical relationships. I had to make some changes for each query function. For example, certain queries required that I define and pass the namespace, while others worked without (the preexisting functions did not use require this). Do you think I should continue to pursue this?
In the meantime, I will use these exec scripts to move on to the issue in the code_embedding repo.

**Comment by carlosparadis** [comment]
Are you saying you can't use this function? 

https://github.com/sailuh/kaiaulu/blob/7e7afbad38fb927063ca3f2d271a9adbaeee925b/R/src.R#L327-L341

I expect the other functions to be more specific:

https://github.com/sailuh/kaiaulu/blob/7e7afbad38fb927063ca3f2d271a9adbaeee925b/R/src.R#L356

and 

https://github.com/sailuh/kaiaulu/blob/7e7afbad38fb927063ca3f2d271a9adbaeee925b/R/src.R#L399

Have their own code logic. I do not expect them to reuse each other. The only reused function is `query_src_text`

Let me know which you are referring a defining a generic function.

Also, your issue specification should be updated to reflect the planned function signatures. That will help disambiguate.

**Comment by daomcgill** [comment]
@carlosparadis I understand that query_src_text is the reusable generic function meant to handle the execution of XPath queries. I can have add a way to call that to the exec script. This will result in an unstructured string representation of the query passed in. Does this sound right to you?

**Comment by daomcgill** [comment]
@carlosparadis here is the diagram so far.
![diagram](https://github.com/user-attachments/assets/076642d4-3036-43c9-ab74-f4363db9fb2f)

**Comment by carlosparadis** [comment]
I just noticed this last week message now. I am assuming you clarified this on call!
