### ISSUE TITLE
Applying Word Embeddings to Source Code for Semantic Analysis Using fastText

### ISSUE THREAD

**Issue by daomcgill** [sailuh/kaiaulu#316]
-----

## Purpose 
The purpose of this issue is to apply word embeddings to the syntax extractions from  [part I](https://github.com/sailuh/kaiaulu/issues/313) and [part II](https://github.com/sailuh/kaiaulu/issues/314) to create semantic representations of source code elements (e.g., class names, functions, documentation). The fastText model will be used to generate vector representations of the meaning and relationships between these code elements. This allows us to measure semantic similarity between different pieces of code, which can be used to reason about about their function, purpose, and meaning beyond the syntax or character strings.

## Process
- Understand how the pieces will fit together, from syntax extraction to embedding generation.
- Understand fastText and how it generates word embeddings.
- Develop a pipeline that takes the extracted code elements into the fastText model and generates embeddings.
- Use WMD for qualitative analysis on the semantic similarity between code.
- Maintain a notebook.

## Task List 
- [ ] Draw a diagram representation of all the moving parts. See this [example](https://github.com/sailuh/kaiaulu/issues/186#issue-1667048891). This diagram should show how code elements are processed, how embeddings are generated, and how WMD will be applied for analysis.
- [ ] Create the pipeline.
- [ ] Apply metrics to measure the embeddings.
- [ ] Document the process and results.

## Word Embeddings
Word embeddings are  a way to represent text (including code embeddings) by mapping it to a vector of decimal numbers in a continuous vector space. The vectors can be used to capture the semantic relationships (via similarities/ differences) between elements. Similarities are based on the context and meaning, not on string representations. Here, we will use code elements as words or phrases. Example: "FullScreen" and "toggleFullScreen" would have similar embeddings, since they are functionally related.

## Model
The fastText pre-trained model is trained on Java source code, and is capable of generating word embeddings that represent the semantic relationship between code elements. When Spinelli (see links in References below) used this model, it was found that variations in the training parameters had significant effects on the generated embeddings. This is why the way we choose to represent source code in [part I](https://github.com/sailuh/kaiaulu/issues/313) and [part II](https://github.com/sailuh/kaiaulu/issues/314) matters. Spinelli found that overly preprocessed data (composite ID layers split and tokens lowercased) led to poor results.

## Metrics
- Word Mover's Distance (WMD): calculates how close two pieces of source code are related semantically, using their positions in vector space. This metric can be used to compare the similarity between code elements.

### References
- [Code Embedding Repo](https://github.com/sailuh/code_embedding)
- [fastText Notebook](https://github.com/sailuh/code_embedding/blob/master/fasttext_java_spinelis.ipynb)
- [fastText GitHub](https://github.com/facebookresearch/fastText) and [website](https://fasttext.cc/)
- [Semantic Source Code Models Using Identifier Embeddings, Spinelli](https://arxiv.org/pdf/1904.06929)
- [Trained Model to Turn Text into Embeddings, Spinelli](https://zenodo.org/records/2558730) (see  java-ftskip-dim100-ws5.bin)

-----

**Comment by daomcgill** [comment]
@carlosparadis part III. Let me know if this should be moved to the code_embedding repo.

**Comment by carlosparadis** [comment]
@daomcgill I will keep this as a placeholder issue for the time being, this should go on the other repo.

**Comment by carlosparadis** [comment]
@daomcgill Let's use this as an extension of the #313. Namely, whereas there you should extract subset of words from srcML to represent a file, here you represent a file by a) the commit messages associated to it, and b) the issue messages they are tied to. 

This may sound a bit confusing, so let me know if you have questions. This will also serve as input to the original issue here.
