### ISSUE TITLE
Creating a File Directory with Functions in /config.R

### ISSUE THREAD

**Issue by crepesAlot** [sailuh/kaiaulu#321]
### Purpose
--------------
In issue #230, the folder organization was reorganized to follow [this](https://github.com/sailuh/kaiaulu/issues/230#issuecomment-2412833105) diagram.
As /config.R is intended to be a central focal point for managing and using the notebooks and configuration files.
Therefore a feature that would greatly assist users would be functions within /config.R that create the recommended folder directory.

### Process
--------------
Create a series of functions within /config.R that build up the folder organization.

### Task List
---------------
- [ ] Create the file directory for the mailing list
- [ ] Create the file directory for the issue tracker
- [ ] Create the file directory for the git_repo & tools
- [ ] Create the file directory for the analysis

**Comment by crepesAlot** [comment]
Considering that there can be multiple project keys for both mailing_list and issue_tracker, I plan to have the functions require the user to specify 2 parameters, the config_file and project_key_index.
For example, when creating a file path:
```
../../rawdata/project_of_interest/github/issues/owner_repo/
```
The parameters would be config_file = project_of_interest.yml, project_key_index = 1.

**Comment by carlosparadis** [comment]
I think what you want here is a function that reads the config file structure, making some assumptions of it, and create the entire folder structure and sub-folders, rather than a function to create one folder.

**Comment by crepesAlot** [comment]
Sorry, I meant to say that I would have 1 function that creates the entire issue_tracker directory, where it would perform the steps in the prior comment for each of the subfolders for github and something similar for bugzilla and jira.
Haven't completely thought out the function to create the mailing_list directory, but may do some kind of loop to get each project_key_index to ensure it gets all the mailing lists for pipermail and mod_mbox.

**Comment by carlosparadis** [comment]
What I am saying is that this issue should have a single function that the user calls.  User should not be calling multiple functions to create folders. The only input to said function is the path to the config file. It has to scan the config file to decide what additional functions to call (e.g. the issue tracker, the mailing list, etc). If the user has to "program folder creation" it will be faster for them to manually create it themselves. 

I suggest you update the issue specification accordingly with the function signatures, and some notion of what function calls what for discussion.

**Comment by crepesAlot** [comment]
@carlosparadis I was able to create the function and have @beydlern test it on his end as well. The directories seem to be created without any problems.
The output looks something like:
```
> create_file_directory(conf)
Created filepath: ../../rawdata/kaiaulu/git_repo/kaiaulu/.git
No mailing_list found
Created filepath: ../../rawdata/kaiaulu/jira/sailuh/issues/
Created filepath: ../../rawdata/kaiaulu/jira/sailuh/issue_comments/
Created filepath: ../../rawdata/kaiaulu/github/sailuh_kaiaulu/issue_or_pr_comment/
Created filepath: ../../rawdata/kaiaulu/github/sailuh_kaiaulu/issue/
Created filepath: ../../rawdata/kaiaulu/github/sailuh_kaiaulu/issue_search/
Filepath: ../../rawdata/kaiaulu/github/sailuh_kaiaulu/issue_event/ already exists.
Created filepath: ../../rawdata/kaiaulu/github/sailuh_kaiaulu/pull_request/
Filepath: ../../rawdata/kaiaulu/github/sailuh_kaiaulu/commit/ already exists.
Invalid filepath: 
No bugzilla found
dv8 is unused
srcml is unused
pattern4 is unused
Created filepath: ../../rawdata/kaiaulu/git_repo/understand/
Filepath: ../../analysis/kaiaulu/understand/ already exists.
```
The `Invalid filepath:` is there because I also added the filepath for discussions to accommodate the discussions endpoint (which isn't yet implemented on this particular branch yet).

**Comment by carlosparadis** [comment]
Thank you for the update!
